### ISSUE TITLE
cargo test fails on rust stable and beta

### ISSUE THREAD

**Issue by Bujiraso** [rickyhan/rasta#1]
Hey Ricky,

I'm seeing the following error while trying to test the project (`cargo test`)
```
error[E0554]: #![feature] may not be used on the stable release channel
 --> src/main.rs:4:1
  |
4 | #![feature(box_syntax)]
  | ^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

Can't seem to build on beta, or stable, so it might be worth adding to the README some build instructions.

**Comment by 0b01** [comment]
You should be able to build it on nightly.

**Comment by Bujiraso** [comment]
Yes, I didn't realize that #2 was not a Rust failure.
Might be worth putting a note in the README but I'll leave it to you :)
